version: "3.9"

services:
  fowldata:  # container name 
      build:
        context: .
        args:
          - DEV="true"
      ports:
        - "8000:8000"
      volumes:
        - ./fowldata:/fowldata
      command: >
        sh -c "python manage.py wait_for_db &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
      environment:
        - DB_HOST=postgres
        - DB_NAME=devdb
        - DB_USER=devuser
        - DB_PASS=mysecretpassword

      depends_on:
        - postgres


  postgres:
    image: postgis/postgis:16-3.4
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=mysecretpassword
    restart: "on-failure"

volumes:
  postgres_data:

