version: "3.9"

services:
  fowldata:
      build:
        context: .
        args:
          - DEV="true"
      ports:
        - "8000:8000"
      volumes:
        - ./fowldata:/fowldata
      command: >
        sh -c "python manage.py runserver 0.0.0.0:8000"
      environment:
        - DB_HOST=postgres
        - DB_NAME=devdb
        - DB_USER=devuser
        - DB_PASS=changeme
      depends_on:
        - postgres

  postgres:
    image: postgres:13-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTRES_USER=devuser
      - POSTRES_PASSWORD=changeme

volumes:
  postgres-data:



