FROM ubuntu:24.04

# BAsic BUilding blocks
RUN apt-get update \
    && apt-get -y install software-properties-common netcat gcc postgresql \
    && apt-get clean 

# Now PROJ
# NOW geos
# NOW GDAL


# Now Python

# Now project files